### ISSUE TITLE
comentario de n capas

### ISSUE THREAD

**Issue by marlonjt** [MicrosoftDocs/architecture-center.es-es#18]
la arquitectura en capas es una forma mas segura a la hora de realizar software ya que ella se puede dividir en capas en la superior inferior la capa superior puede utilizar servicios también y también a la hora de trabajar en maquinas separadas se puede interactuar , esta sirve para interactuar los proyectos de infra estructura esta administra los datos en cache los mensajes y la almacenamiento de datos.
 los servicios en n capas sirven para  web simples y así enviar a la nube como Azure   y tener proyectos tradicionales o  simples.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5e5ad897-88ad-5298-b9ff-4d988af52466
* Version Independent ID: 8a3904d9-17ed-0ac0-f006-6997095c86bb
* Content: [Estilo de arquitectura de n niveles - Azure Application Architecture Guide](https://docs.microsoft.com/es-es/azure/architecture/guide/architecture-styles/n-tier#feedback)
* Content Source: [docs/guide/architecture-styles/n-tier.md](https://github.com/microsoftdocs/architecture-center.es-es/blob/live/docs/guide/architecture-styles/n-tier.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by ticianaciminari** [comment]
Hola, @

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
