### ISSUE TITLE
Aplicación de n niveles ( Capas)

### ISSUE THREAD

**Issue by stefanysamaniego** [MicrosoftDocs/architecture-center.es-es#20]
Por lo que pude comprender, la arquitectura en capas yo lo relaciono con Angular ya que trabaja con componente, las cuales permiten trabajar en una aplicación web por partes, tal y como lo hace esta metodología.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5e5ad897-88ad-5298-b9ff-4d988af52466
* Version Independent ID: 8a3904d9-17ed-0ac0-f006-6997095c86bb
* Content: [Estilo de arquitectura de n niveles - Azure Application Architecture Guide](https://docs.microsoft.com/es-es/azure/architecture/guide/architecture-styles/n-tier#feedback)
* Content Source: [docs/guide/architecture-styles/n-tier.md](https://github.com/microsoftdocs/architecture-center.es-es/blob/live/docs/guide/architecture-styles/n-tier.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by stalin1997** [comment]
Una arquitectura de n niveles divide una aplicación en capas lógicas y niveles físicos, estas son una forma de separar responsabilidades y administrar dependencias. Cada una de ellas tiene una responsabilidad específica. Una capa superior puede utilizar los servicios de una capa inferior, pero no al revés.Un nivel puede llamar a otro nivel directamente o usar mensajería asincrónica 
Una aplicación con n niveles puede tener 

Una arquitectura de capa cerrada : una capa solo puede llamar a la capa inmediatamente inferior.

Y una arquitectura de capa abierta: una capa puede llamar a cualquiera de las capas que se encuentran debajo de ella.
Las arquitecturas de n niveles se implementan normalmente como aplicaciones de infraestructura como servicio 

Ventajas

Portabilidad entre la nube y entornos locales, y entre plataformas en la nube.

Evolución natural desde el modelo de aplicaciones tradicional


Configurar el nivel de base de datos para lograr alta disponibilidad, mediante una solución como grupos de disponibilidad de SQL Server Always On.

Coloque un firewall de aplicaciones web (WAF) entre el front-end e Internet.

Coloque cada nivel en su propia subred y utilice las subredes como límite de seguridad.

Procedimientos recomendados

Utilice el escalado automático para tratar los cambios en la carga. Consulte Procedimientos recomendados de escalado automático

Utilice la mensajería asincrónica para desacoplar niveles.

Almacenar en caché datos semistatic.Consulte Procedimientos recomendados para el almacenamiento en caché.

Configurar el nivel de base de datos para lograr alta disponibilidad.

Coloque un firewall de aplicaciones web (WAF) entre el front-end e Internet.

Coloque cada nivel en su propia subred y utilice las subredes como límite de seguridad.
Varias máquinas virtuales ofrecen resistencia en caso de que se produzca un error en una máquina virtual. Los equilibradores de carga se utilizan para distribuir solicitudes a través de las máquinas virtuales de un nivel. 
Cada nivel también se coloca dentro de su propia subred, lo que significa que sus direcciones IP internas están dentro del mismo rango de direcciones.

**Comment by ticianaciminari** [comment]
Hola, @stefanysamaniego 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
