### ISSUE TITLE
Quinaluisa Carlos

### ISSUE THREAD

**Issue by KH0RE** [MicrosoftDocs/architecture-center.es-es#24]
Esta arquitectura es tradicional para aplicaciones empresariales, sus representaciones son de manera lógica de negocios. Los sistemas horizontales tienen otros defectos, esto hace que sea más complicado, haciendo que sea dificil hacer cambios , por otra parte las actualizaciones son otro problema
Con esta arquitectura es habitual para migrar aplicaciones y son usadas frecuentemente para soluciones de infraestructura

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5e5ad897-88ad-5298-b9ff-4d988af52466
* Version Independent ID: 8a3904d9-17ed-0ac0-f006-6997095c86bb
* Content: [Estilo de arquitectura de n niveles - Azure Application Architecture Guide](https://docs.microsoft.com/es-es/azure/architecture/guide/architecture-styles/n-tier)
* Content Source: [docs/guide/architecture-styles/n-tier.md](https://github.com/microsoftdocs/architecture-center.es-es/blob/live/docs/guide/architecture-styles/n-tier.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Hola, @KH0RE

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
