### ISSUE TITLE
Ventajas

### ISSUE THREAD

**Issue by fercho2798** [MicrosoftDocs/architecture-center.es-es#25]
hay una gran ventaja al aprender la arquitectura n en capas y es que se nos resulta mas fácil aprender para los desarrolladores de software que recién van aprendiendo sobre en los niveles de las maquinas virtuales y que cada una consta con dos maquinas virtuales, gracias por la explicación sobre este tema.    

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5e5ad897-88ad-5298-b9ff-4d988af52466
* Version Independent ID: 8a3904d9-17ed-0ac0-f006-6997095c86bb
* Content: [Estilo de arquitectura de n niveles - Azure Application Architecture Guide](https://docs.microsoft.com/es-es/azure/architecture/guide/architecture-styles/n-tier#feedback)
* Content Source: [docs/guide/architecture-styles/n-tier.md](https://github.com/microsoftdocs/architecture-center.es-es/blob/live/docs/guide/architecture-styles/n-tier.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by marlonjt** [comment]
y cree que es recomendable utilizar los n capas para realizar algún proyecto

**Comment by ticianaciminari** [comment]
Hola, @fercho2798 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
