### ISSUE TITLE
Mario Soledispa

### ISSUE THREAD

**Issue by MarioBJAlexander** [MicrosoftDocs/architecture-center.es-es#26]
Una arquitectura de n niveles divide una aplicación en capas lógicas y niveles físicos
Las capas son una forma de separar responsabilidades y administrar dependencias. Cada capa tiene una responsabilidad específica. Una capa superior puede utilizar los servicios de una capa inferior, pero no al revés.
Los niveles están físicamente separados y se ejecutan en máquinas diferentes. Un nivel puede llamar a otro nivel directamente o usar mensajería asincrónica.
Una aplicación con n niveles puede tener una arquitectura de capa cerrada o una arquitectura de capa abierta:
En la arquitectura de capa cerrada, una capa solo puede llamar a la capa inmediatamente inferior.
En una arquitectura de capa abierta, una capa puede llamar a cualquiera de las capas que se encuentran debajo de ella.

**Comment by ticianaciminari** [comment]
Hola, @MarioBJAlexander 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
