### ISSUE TITLE
Comentario

### ISSUE THREAD

**Issue by marlonjt** [MicrosoftDocs/architecture-center.es-es#27]
Esta arquitectura es tradicionales que nos pernite varias arquitecturas y aplicaciones que nos pernite realizar funciones logicas y que nos permite realizar las arquitecturas que se puedan encontrar frecuente mente con un servicio o aplicación para que las empresas puedan utilizarlas

**Comment by ticianaciminari** [comment]
Hola, @marlonjt 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
