### ISSUE TITLE
Delgado Byron

### ISSUE THREAD

**Issue by Delgadoby12** [MicrosoftDocs/architecture-center.es-es#28]
La programación por capas es una arquitectura cliente-servidor en el que el objetivo primordial es la separación de la lógica de diseño de software; un ejemplo básico de esto consiste en separar la capa de datos de la capa de presentación.
En el diseño de sistemas informáticos actual se suelen usar las arquitecturas multinivel o Programación por capas. 
En dichas arquitecturas a cada nivel se le confía una misión simple, lo que permite el diseño de arquitecturas escalables (que pueden ampliarse con facilidad en caso de que las necesidades aumenten).

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5e5ad897-88ad-5298-b9ff-4d988af52466
* Version Independent ID: 8a3904d9-17ed-0ac0-f006-6997095c86bb
* Content: [Estilo de arquitectura de n niveles - Azure Application Architecture Guide](https://docs.microsoft.com/es-es/azure/architecture/guide/architecture-styles/n-tier#feedback)
* Content Source: [docs/guide/architecture-styles/n-tier.md](https://github.com/microsoftdocs/architecture-center.es-es/blob/live/docs/guide/architecture-styles/n-tier.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by KH0RE** [comment]
Quinaluisa Carlos 
También se puede añadir los siguiente
Esta arquitectura es tradicional para aplicaciones empresariales, sus representaciones son de manera lógica de negocios. Los sistemas horizontales tienen otros defectos, esto hace que sea más complicado, haciendo que sea dificil hacer cambios , por otra parte las actualizaciones son otro problema
Con esta arquitectura es habitual para migrar aplicaciones y son usadas frecuentemente para soluciones de infraestructura

**Comment by ticianaciminari** [comment]
Hola, @Delgadoby12 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
