### ISSUE TITLE
N Capas

### ISSUE THREAD

**Issue by DavidRivera99** [MicrosoftDocs/architecture-center.es-es#33]
David Rivera
Las arquitecturas de n niveles se implementan normalmente como aplicaciones de infraestructura como servicio (IaaS), donde cada nivel se ejecuta en un conjunto independiente de máquinas virtuales. Sin embargo, una aplicación de n niveles no tiene que ser IaaS puro. A menudo, resulta ventajoso utilizar servicios administrados para algunas partes de la arquitectura, en particular el almacenamiento en caché, la mensajería y el almacenamiento de datos.
Considere una arquitectura de n niveles para:
Aplicaciones web simples.
La migración de una aplicación local a Azure con mínima refactorización.
El desarrollo unificado de aplicaciones locales y en la nube.
Las arquitecturas de n niveles son muy comunes en las aplicaciones locales tradicionales, por lo que es una opción ideal para migrar las cargas de trabajo existentes a Azure.

**Comment by ticianaciminari** [comment]
Hola, @

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
