### ISSUE TITLE
Documentación 

### ISSUE THREAD

**Issue by jjvduncan** [MicrosoftDocs/architecture-center.es-es#36]
La documentación es muy interesante aunque la ultima actualización de   para este año, existen muchos cambios o no, ya que cada año cambian cosas muy importantes

**Comment by CeciAc** [comment]
Hola, @jjvduncan

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas. 

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia. 

Atentamente, 
Equipo internacional de Microsoft Docs
