### ISSUE TITLE
Documentacion

### ISSUE THREAD

**Issue by jjvduncan** [MicrosoftDocs/architecture-center.es-es#37]
La documentación es muy importante, pero los cambios realizados para  este año son muchos o pocos los cambios, ya que seria manejar mas ejemplos prácticos,  y ver que tipo de proyectos podemos aplicar

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5e5ad897-88ad-5298-b9ff-4d988af52466
* Version Independent ID: 8a3904d9-17ed-0ac0-f006-6997095c86bb
* Content: [Estilo de arquitectura de n niveles - Azure Application Architecture Guide](https://docs.microsoft.com/es-es/azure/architecture/guide/architecture-styles/n-tier#feedback)
* Content Source: [docs/guide/architecture-styles/n-tier.md](https://github.com/microsoftdocs/architecture-center.es-es/blob/live/docs/guide/architecture-styles/n-tier.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Hola, @jjvduncan
Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas. 

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia. 

Atentamente, 
Equipo internacional de Microsoft Docs
