### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by jjvduncan** [MicrosoftDocs/architecture-center.es-es#38]
1.- El CDN es necesario, para realizar la cola de trabajo,  y porque parte de variables estáticas.
2.- SI la web y el trabajo no tienen estado, como se en que momento estoy afuera o dentro del sistema

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 495b2ac1-3a9c-d1db-2b46-bbfbd0a4b538
* Version Independent ID: 2f6008fa-9b45-6ce1-13b5-74f82550f715
* Content: [Estilo de arquitectura web-cola-trabajo - Azure Application Architecture Guide](https://docs.microsoft.com/es-es/azure/architecture/guide/architecture-styles/web-queue-worker)
* Content Source: [docs/guide/architecture-styles/web-queue-worker.md](https://github.com/microsoftdocs/architecture-center.es-es/blob/live/docs/guide/architecture-styles/web-queue-worker.md)
* Service: **architecture-center**
* Sub-service: **cloud-fundamentals**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Hola, @jjvduncan

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
